

# Get data from Contentful
contentful:
  output: true
  spaces:
    - updates: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'update'
        all_entries: true
        destination: 'contentful/spaces/'
    - newsrooms: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'newsroom'
        all_entries: true
        destination: 'contentful/spaces/'
    - landingPages: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'landingPage'
        all_entries: true
        destination: 'contentful/spaces/'
    - homepages: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'homepage'
        all_entries: true
        destination: 'contentful/spaces/'
    - stats: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'stat'
        all_entries: true
        destination: 'contentful/spaces/'
    - media: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'media'
        all_entries: true
        destination: 'contentful/spaces/'
    - sections: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'section'
        all_entries: true
        destination: 'contentful/spaces/'
    - colors: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'color'
        all_entries: true
        destination: 'contentful/spaces/'
    - locations: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'location'
        all_entries: true
        destination: 'contentful/spaces/'
    - links: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'link'
        all_entries: true
        destination: 'contentful/spaces/'
    - cards: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleCard'
        all_entries: true
        destination: 'contentful/spaces/'
    - graphics: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleGraphic'
        all_entries: true
        destination: 'contentful/spaces/'
    - images: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleImage'
        all_entries: true
        destination: 'contentful/spaces/'
    - leadImages: 
        space: ENV_CONTENTFUL_PN_SPACE_ID
        access_token: ENV_CONTENTFUL_PN_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleLeadImage'
        all_entries: true
        destination: 'contentful/spaces/'


# Generate pages from Contentful data files
page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.newsrooms.newsroom'
    template: 'newsroom'
    name: 'url'
    dir: 'newsrooms'
  - data: 'contentful.spaces.landingPages.landingPage'
    template: 'landing'
    name: 'url'
    dir: 'pages'